const words = [
  {
    title: "adelgazar",
    ranking: "421",
    phrases: [
      "se volvio para adelgazar un poco de mas",
      "ademas, se decidio a adelgazar sin ambargo",
    ],
    synonyms: ["amincir", "minorar"],
    antonyms: ["asd"],
    concurrences: ["asd"],
    meanings: ["asd"],
    in_english: "asd",
    register_difficulty: "familiar, any",
    type: "verb",
    verb_participe: "adelgazado",
    verb_group: "regular",
    prefix: "de",
    suffix: "ion",
    gender: "feminine",
  },
  {
    title: "arreglar",
    ranking: "321",
    phrases: ["mi correo puedes arreglar", "el coche se necesita arreglar"],
    synonyms: ["fijar", "corregir"],
    type: "verb",
    verb_participe: "arreglado",
    verb_group: "regular",
  },
  {
    title: "ver",
    ranking: "17",
    phrases: ["estaba mirando desde la ventana", "mire sus ojos calientemente"],
    synonyms: ["mirar", "minorar"],
    type: "conj",
    verb_participe: "visto",
    verb_group: "irregular",
  },
  {
    title: "borrar",
    ranking: "217",
    phrases: ["estaba mirando desde la ventana", "mire sus ojos calientemente"],
    synonyms: ["mirar", "minorar"],
    type: "verb",
    verb_participe: "adelgazado",
    verb_group: "regular",
  },
  {
    title: "casar",
    ranking: "87",
    phrases: ["estaba mirando desde la ventana", "mire sus ojos calientemente"],
    synonyms: ["mirar", "minorar"],
    type: "adj",
    verb_participe: "casado",
    verb_groups: ["regular", "reflexivo", "modal", "transitivo"],
  },
  {
    title: "demasiada",
    ranking: "147",
    phrases: ["estaba mirando desde la ventana", "mire sus ojos calientemente"],
    synonyms: ["mirar", "minorar"],
    type: "conj",
    verb_participe: "",
    verb_group: "",
  },
  {
    title: "cuidamente",
    ranking: "147",
    phrases: ["estaba mirando desde la ventana", "mire sus ojos calientemente"],
    synonyms: ["mirar", "minorar"],
    type: "adv",
    verb_participe: "",
    verb_group: "",
  },
];

export default words;
